# app/config/config.yml (or config/packages/knp_snappy.yaml if using Symfony4 and the Flex recipe)
knp_snappy:

  temporary_folder: "%kernel.cache_dir%/snappy"

  process_timeout: 60

  pdf:
    enabled:    true
    binary:     'C:\wkhtmltox\bin\wkhtmltopdf.exe'
    options:    []
  image:
    enabled:    true
    binary:     'C:\wkhtmltox\bin\wkhtmltoimage.exe'
    options:    []