import '../../shared/script/index';
import './navBarOffCanvas.ts';
import './offcanvas.ts';
import './panierToggle.ts';
import './showPassword.ts';
import './gestionCompteToggle.ts';
import './addItemToCart.ts';
import './selectPaiement.ts';
import './orderAjax.ts';